project:
  type: book

book:
  title: "Mapping"
  author: 
    - name: Seamus Murphy
      url: https://scholar.google.com/citations?hl=en&user=jDGq9I4AAAAJ
      orcid: 0000-0002-1792-0351 
      email: seamusrobertmurphy@gmail.com
  date: today
  favicon: ./assets/PNG/favicon.png
  open-graph: true 
  page-footer:
    left: "[Source](https://github.com/seamusrobertmurphy/map-templates)"

  site-url: https://seamusrobertmurphy.quarto.pub/map-templates
  repo-url: https://github.com/seamusrobertmurphy/map-templates
  repo-branch: main
  repo-actions: [edit, issue]

  tools:
    - icon: linkedin
      href: https://linkedin.com/in/seamusrobertmurphy
      text: "LinkedIn"
    - icon: file-earmark-pdf
      href: https://drive.google.com/uc?export=download&id=13YLhsRCAMMHQw-jd2SJdaRJH9udBGytP
      text: "Resume"
    - icon: mortarboard
      href: https://scholar.google.com/citations?hl=en&user=jDGq9I4AAAAJ
      text: "Scholar"

website:
  title: "Mapping Templates"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    title: "Map Templates"
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Sites"
        href: site-map.qmd
      - text: "Watersheds"
        href: watershed-map.qmd
      - text: "Riparian"
        href: stream-map.qmd 
      - text: "Topography"
        href: topo-map.qmd 
      - text: "Climate"
        href: climate-map.qmd
      - text: "Demography"
        href: population-map.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/seamusrobertmurphy
          - text: Report a Bug
            href: https://github.com/seamusrobertmurphy
      - icon: linkedin
        href: https://linkedin.com/in/seamusrobertmurphy
      
  sidebar:
      pinned: true
      style: "docked"
      collapse-level: 1
      contents:
      - text: "Home"
        href: index.qmd
      - text: "1 Site Maps"
        href: site-map.qmd
      - text: "2 Watershed Maps"
        href: watershed-map.qmd
      - text: "3 Riparian Maps"
        href: stream-map.qmd 
      - text: "4 Topography Maps"
        href: topo-map.qmd 
      - text: "5 Climate Maps"
        href: climate-map.qmd
      - text: "6 Demography Maps"
        href: population-map.qmd
      - section: "About"
        contents:
          - text: "Resume"
            href: about.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    fig-width: 8
    fig-height: 6
    fig-dpi: 150  
    fig-format: png
engine: knitr